version: '3.9'

services:
  database:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - ./Database/config/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./Database/postgres:/var/lib/postgresql/data
    env_file:
      - ./Database/config/database.env
    networks:
      int:
        ipv4_address: 10.200.0.2
    ports:
      - '5432:5432'

  web:
    #depends_on:
      #- database
    container_name: web
    build: ./Web
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/APP/
    networks:
      int:
        ipv4_address: 10.200.0.3
      ext:
        ipv4_address: 192.168.0.3
    ports:
      - '8000:8000'

networks:
  int:
    name: django-interno
    driver: bridge
    #driver_opts:
      #parent: wlo1
    ipam:
      driver: default
      config:
        - subnet: 10.200.0.0/24  
          gateway: 10.200.0.1
  ext:
    external:
      name: ext

volumes:
  django: